# Generated by Django 4.2.7 on 2023-11-15 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
