# Generated by Django 4.2.6 on 2023-11-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciseset",
            name="number",
        ),
        migrations.AlterField(
            model_name="exerciseconf",
            name="default_reps",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="exerciseconf",
            name="default_set_number",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="exerciseconf",
            name="default_weight",
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name="exerciseconf",
            name="max_weight",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
