# Generated by Django 4.2.6 on 2023-11-09 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_remove_exerciseset_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="date",
            field=models.DateField(default=datetime.date(2023, 11, 9)),
        ),
    ]
