# Generated by Django 4.2.7 on 2023-11-16 05:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workout.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key="True", serialize=False
                    ),
                ),
                (
                    "sets",
                    models.JSONField(default=workout.models.BaseExercise.default_sets),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key="True", serialize=False
                    ),
                ),
                ("config", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField(default=datetime.date(2023, 11, 16))),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key="True", serialize=False
                    ),
                ),
                (
                    "sets",
                    models.JSONField(default=workout.models.BaseExercise.default_sets),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutlog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomWorkout",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key="True", serialize=False
                    ),
                ),
                ("config", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomExercise",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key="True", serialize=False
                    ),
                ),
                (
                    "sets",
                    models.JSONField(default=workout.models.BaseExercise.default_sets),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
