 on:
   workflow_run:
     workflows: ["Django CI"]
     types: [completed] #requested

 jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - run: echo "First workflow was a success"
   create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout -b feature-branch
        git commit -am "Add new feature"
        git push -u origin feature-branch

        hub pull-request -b main -h feature-branch -m "Merge feature-branch into main" -F- <<EOF
        This is an automated pull request created by GitHub Actions.
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge Pull Request
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git fetch
        git pull origin main
        git branch -D feature-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
