 on:
   workflow_run:
     workflows: ["Django CI"]
     types: [completed] #requested

 jobs:
   create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      run: |
        git config --global user.name 'SeanNorini'
        git config --global user.email 'snorini@gmail.com'
        git checkout -b dev
        git commit -am "Add new feature"
        git push -u origin dev

        hub pull-request -b main -h dev -m "Merge dev into main" -F- <<EOF
        This is an automated pull request created by GitHub Actions.
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge Pull Request
      run: |
        git config --global user.name 'SeanNorini'
        git config --global user.email 'snorini@gmail.com'
        git fetch
        git pull origin main
        git branch -D dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
