 name: Merge Pull Request
 on:
   workflow_run:
     workflows: ["Create Pull Request"]
     types: [completed] #requested
   workflow_dispatch:

 jobs:
   merge_pull_request:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: "Approve pull request"
      uses: "actions/github-script@v5"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          const pullRequest = context.payload.workflow_run.pull_requests[0]
          console.log(pullRequest.number)

