 name: Create Pull Request
 on:
   workflow_run:
     workflows: ["Create Pull Request"]
     types: [completed] #requested

 jobs:
   create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: test
    steps:
  
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Merge Pull Request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });
          console.log(`Pull Request #${prNumber} merged.`);
