name: Merge Branch

on:
  pull_request:
    branches:
      - main

jobs:
  merge_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Branch
        run: |
          target_branch="main"

          if [ "${{ github.event.pull_request.base.ref }}" == "$target_branch" ]; then
            echo "Skipping merge as it's a pull request to the 'main' branch."
            exit 0
          fi

          git checkout -B $target_branch
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin $target_branch

          if git log --merges -n 1 --oneline | grep -q "Merge branch"; then
            echo "Conflicts detected. Manual intervention required."
          else
            echo "Branch merged successfully."
          fi
