name: Auto-Approve and Merge

on:
  pull_request:
    types:
      - opened
  workflow_run:
     workflows: ["Create Pull Request"]
     types: [completed] #requested
   workflow_dispatch:

jobs:
  auto_approve_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is Mergeable
        run: |
          # Check if the pull request is mergeable
          PR_NUMBER=${{ github.event.pull_request.number }}
          IS_MERGEABLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.mergeable')

          if [ "$IS_MERGEABLE" = "true" ]; then
            echo "Pull Request is mergeable."
          else
            echo "Pull Request is not mergeable."
            exit 1
          fi

      - name: Auto-Approve PR
        run: |
          # Approve the pull request
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEW_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST -d '{"event": "APPROVE"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | jq -r '.id')

          if [ -n "$REVIEW_ID" ]; then
            echo "Pull Request approved."
          else
            echo "Failed to approve the pull request."
            exit 1
          fi

      - name: Merge PR
        run: |
          # Merge the pull request
          PR_NUMBER=${{ github.event.pull_request.number }}
          MERGE_RESULT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X PUT "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge")

          if [[ "$MERGE_RESULT" == *"merged"* ]]; then
            echo "Pull Request merged."
          else
            echo "Failed to merge the pull request."
            exit 1
          fi

