name: Create Pull Request
on:
  workflow_run:
   workflows: ["Django Tests"]
   types: [completed] #requested
  workflow_dispatch:
jobs:
  create_pull_request:
   runs-on: ubuntu-latest
   
   steps:
   - name: Checkout code
     uses: actions/checkout@v2


   - name: Create Pull Request
     uses: actions/github-script@0.9.0
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       script: |
         const title = "Create Pull Request";
         const head = "dev";
         const base = "main";
         const body = "Description of your pull request.";

         const pr = await github.pulls.create({
           owner: context.repo.owner,
           repo: context.repo.repo,
           title,
           head,
           base,
           body,
         })
         .then(response => {
         const PR_NUMBER = response.data.number
         console.log(PR_NUMBER)
         core.exportVariable("PR_NUMBER", PR_NUMBER)
         });

         await github.pulls.createReview({
              event: "APPROVE",
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: PR_NUMBER,
            })

         await github.pulls.merge({
              merge_method: "merge",
              owner: context.repo.owner,
              pull_number: PR_NUMBER,
              repo: context.repo.repo,
            })
