 name: Create Pull Request
 on:
   workflow_dispatch:
 jobs:
   create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Create Pull Request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = "Create Pull Request";
          const head = "dev";
          const base = "main";
          const body = "Description of your pull request.";

          const pr = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            head,
            base,
            body,
          });
          
    - name: Extract Pull Request Number
      id: extract_pr_number
      run: |
        PR_NUMBER=$(echo "$GITHUB_REF" | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      shell: bash
      
    - name: Merge Pull Request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          env: PR_NUMBER
          const prNumber=PR_NUMBER
          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });
          console.log(`Pull Request #${prNumber} merged.`);
     
          
           
