 name: Create Pull Request
 on:
   workflow_run:
     workflows: ["Django Tests"]
     types: [completed] #requested

 jobs:
   create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Create Pull Request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = "Create Pull Request";
          const head = "dev";
          const base = "main";
          const body = "Description of your pull request.";

          const pr = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            head,
            base,
            body,
          });
            
            // Capture the pull request number
            const prNumber = pr.data.number;

            // Output the pull request number to the workflow logs
            console.log(`Pull Request created: ${pr.data.html_url}`);
            console.log(`Pull Request Number: ${prNumber}`);

            // Set the pull request number as an environment variable
            core.setOutput('pr_number', prNumber);

    - name: Save Pull Request Number
      run: |
       echo "PR_NUMBER=${{ steps.create_pr.outputs.pr_number }}" >> $GITHUB_ENV
           
