name: Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Create Pull Request
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Create Pull Request";
            const head = "dev";  // Replace with your feature branch name
            const base = "main";  // Replace with your target branch name
            const body = "Description of your pull request.";

            const pr = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              head,
              base,
              body,
            });

            console.log(`Pull Request created: ${pr.data.html_url}`);